FROM golang:1.25-alpine AS builder
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:3.22
COPY --from=builder /go/bin/goose /usr/local/bin/goose
ARG MIGRATIONS_PATH=migrations
COPY ${MIGRATIONS_PATH}/ /migrations/
ENTRYPOINT ["goose", "-dir", "/migrations", "postgres"]
